spec:
  podSelector:
    matchLabels:
      app: ong-donation-worker

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: monitoring
      - podSelector:
          matchLabels:
            app: prometheus
      ports:
      - protocol: TCP
        port: 8080

  egress:
    - {}